import { useState } from 'react'
import { useTranslation } from 'react-i18next'

export interface AboutAccordionProps {
  companyName: string
  sector?: string | null
  country?: string | null
  // 2-3 sentence plain-English summary generated by the About AI prompt.
  businessDescription?: string | null
  // Raw Yahoo Finance longBusinessSummary text. Shown only when the user
  // explicitly expands the "Read full description" toggle.
  longBusinessSummary?: string | null
}

export default function AboutAccordion({
  companyName,
  sector,
  country,
  businessDescription,
  longBusinessSummary,
}: AboutAccordionProps) {
  const { t } = useTranslation()
  const [open, setOpen] = useState(false)
  const [showFull, setShowFull] = useState(false)

  const summary = (businessDescription || '').trim()
  const fullText = (longBusinessSummary || '').trim()
  const hasContent = !!(summary || fullText)
  const hasFull = !!fullText && fullText !== summary

  const subParts = [sector, country].filter((s): s is string => !!s && !!s.trim())
  const subtitle = subParts.join(' · ')

  return (
    <section
      className="rounded-2xl border border-gray-100 bg-white shadow-sm overflow-hidden"
      aria-label={t('about.header', { name: companyName })}
    >
      <button
        type="button"
        onClick={() => setOpen((p) => !p)}
        aria-expanded={open}
        className="w-full flex items-start justify-between gap-3 px-4 py-3 text-start hover:bg-gray-50 transition-colors"
      >
        <div className="min-w-0 flex-1">
          <div
            className="text-[13px] font-medium text-gray-900 truncate"
            dir="auto"
          >
            {t('about.header', { name: companyName })}
          </div>
          {subtitle ? (
            <div className="text-[11px] text-gray-500 truncate mt-0.5" dir="auto">
              {subtitle}
            </div>
          ) : null}
        </div>
        <span
          aria-hidden
          className="text-gray-400 text-[12px] leading-none mt-1 shrink-0 select-none"
        >
          {open ? '▴' : '▾'}
        </span>
      </button>

      {open ? (
        <div className="px-4 pb-4">
          <div className="border-t border-gray-100 pt-3">
            {hasContent ? (
              <>
                {summary ? (
                  <p
                    className="text-[13px] text-gray-900"
                    style={{ lineHeight: 1.75 }}
                    dir="auto"
                  >
                    {summary}
                  </p>
                ) : null}

                {hasFull ? (
                  <>
                    <button
                      type="button"
                      onClick={() => setShowFull((p) => !p)}
                      aria-expanded={showFull}
                      className="mt-2 text-[12px] font-medium hover:underline"
                      style={{ color: '#185FA5' }}
                    >
                      {showFull
                        ? `${t('about.hideFull')} ▴`
                        : `${t('about.readFull')} ▾`}
                    </button>

                    {showFull ? (
                      <p
                        className="mt-2 text-[12px] text-gray-600 whitespace-pre-line"
                        style={{ lineHeight: 1.7 }}
                        dir="auto"
                      >
                        {fullText}
                      </p>
                    ) : null}
                  </>
                ) : null}
              </>
            ) : (
              <p className="text-[12px] text-gray-500" dir="auto">
                {t('about.unavailable')}
              </p>
            )}
          </div>
        </div>
      ) : null}
    </section>
  )
}
